// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQDIb1jKp7GKzsz5Rh8Jrqje75x11DWYE',
    appId: '1:717965089195:web:25e54457a7055fab8bdaee',
    messagingSenderId: '717965089195',
    projectId: 'test-projects-6755f',
    authDomain: 'test-projects-6755f.firebaseapp.com',
    storageBucket: 'test-projects-6755f.appspot.com',
    measurementId: 'G-P34LXFGN3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJZzddjyw6WVV9Nh2B-S4VR9Pfo4c0uA',
    appId: '1:717965089195:android:b751d6f0ba844d1b8bdaee',
    messagingSenderId: '717965089195',
    projectId: 'test-projects-6755f',
    storageBucket: 'test-projects-6755f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4J9mu94yZ03N_ytwqFePIIZAY-nIf1R0',
    appId: '1:717965089195:ios:7231e360184443668bdaee',
    messagingSenderId: '717965089195',
    projectId: 'test-projects-6755f',
    storageBucket: 'test-projects-6755f.appspot.com',
    iosBundleId: 'com.example.dxhTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4J9mu94yZ03N_ytwqFePIIZAY-nIf1R0',
    appId: '1:717965089195:ios:ca9453f437f13a588bdaee',
    messagingSenderId: '717965089195',
    projectId: 'test-projects-6755f',
    storageBucket: 'test-projects-6755f.appspot.com',
    iosBundleId: 'com.example.dxhTest.RunnerTests',
  );
}
